name: Publish Package

on:
  push:
    tags:
      - "create-steel-app*" # # Push events to matching create-steel-app*, i.e. create-steel-app@1.0.0

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'steel-dev/steel-cookbook'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Publish package
        run: pnpm publish --no-git-checks --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
